In [1]:
import pandas as pd
import gzip
from pathlib import Path
import json

In [20]:
data_folder = Path("Resources/")
rev_path = data_folder/"Grocery_and_Gourmet_Food.json.gz"
meta_path = data_folder/"meta_Grocery_and_Gourmet_Food.json.gz"
csv_folder = Path("df/")

In [3]:
#For parsing gzip files
def parse(path):
    g = gzip.open(path, 'rb')
    for l in g:
        yield json.loads(l)

In [4]:
#Reading in metadata about the different products
ama_meta = []

for i in parse(meta_path):
    ama_meta.append(i)

In [5]:
print(ama_meta[0])

{'category': ['Grocery & Gourmet Food', 'Dairy, Cheese & Eggs', 'Cheese', 'Gouda'], 'tech1': '', 'description': ['BEEMSTER GOUDA CHEESE AGED 18/24 MONTHS', 'Statements regarding dietary supplements have not been evaluated by the FDA and are not intended to diagnose, treat, cure, or prevent any disease or health condition.'], 'fit': '', 'title': 'Beemster Gouda - Aged 18/24 Months - App. 1.5 Lbs', 'also_buy': [], 'tech2': '', 'brand': 'Ariola Imports', 'feature': [], 'rank': '165,181 in Grocery & Gourmet Food (', 'also_view': ['B0000D9MYM', 'B0000D9MYL', 'B00ADHIGBA', 'B00H9OX598', 'B001LM42GY', 'B001LM5TDY'], 'main_cat': 'Grocery', 'similar_item': '', 'date': '', 'price': '$41.91', 'asin': '0681727810', 'imageURL': [], 'imageURLHighRes': []}

In [6]:
#Storing the asin codes and the product data for tinned fish products
ama_meta_trim = []
asin = []
for entry in ama_meta:
    if 'Canned, Jarred & Packaged Foods' in entry['category'] and 'Seafood' in entry['category']:
        
        product = {'fish': entry['category'][-1], 'name': entry['title'], 'asin': entry['asin']} 
        
        ama_meta_trim.append(product)
        asin.append(entry['asin'])
print(asin)

['5643467860', 'B0000D17CF', 'B0000SX9YQ', 'B0000SX9U0', 'B0000TUA7O', 'B00017Y986', 'B0001990A6', 'B0001ENXJK', 'B0001GUQ3O', 'B0001M1240', 'B0002CNZJO', 'B0002CO0DE', 'B0002QMA3M', 'B0000D17CF', 'B0000SX9YQ', 'B0000SX9U0', 'B0000TUA7O', 'B00017Y986', 'B0001990A6', 'B0001ENXJK', 'B0001GUQ3O', 'B0001M1240', 'B0002CNZJO', 'B0002CO0DE', 'B0002QMA3M', 'B0005YL6SG', 'B0005ZH3DM', 'B00060NHG8', 'B00060NH9A', 'B000677SES', 'B0006UFY46', 'B00078N8TU', 'B0007DDHFK', 'B0008IT4GK', 'B00099XMHA', 'B000BTHHF6', 'B000C04I24', 'B000CQZXU4', 'B000CR1VYU', 'B000CR1VUY', 'B000CR1VXQ', 'B000CR3YVI', 'B000CR3Z0I', 'B000CRIFGM', 'B000EEWZEG', 'B000EEWZG4', 'B000EEWZF0', 'B000EEZ3MW', 'B000EEWZBY', 'B000EEZ3LI', 'B000EEZ3LS', 'B000EF3E5O', 'B000EF3E54', 'B000EFIJSQ', 'B000EMK3VU', 'B000EMM9EY', 'B000FAKUQY', 'B000FDCS0C', 'B000FDLBLY', 'B000FDN78Y', 'B000FDP6GA', 'B000FDP6IS', 'B000FEH6N0', 'B000GF56OY', 'B000H2293C', 'B000HDJZEM', 'B000HDJYX4', 'B000HDJZEC', 'B000HDL1B2', 'B000HDL16C', 'B000HDMW8S', 'B000HDMW9M', 'B000HDMWC4', 'B000HDL1DK', 'B000HDOP60', 'B000HDOPNS', 'B000HDOPHE', 'B000HDOPGA', 'B000HEICVS', 'B000HQMNFC', 'B000HQNC52', 'B000HQR2EY', 'B000II0GCG', 'B000ITVLE2', 'B000ITVLI8', 'B000ITUEBS', 'B000ITYSYC', 'B000ITWX2G', 'B000JDHSAI', 'B000K8SXN8', 'B000KHGSKO', 'B000KHIRZS', 'B000KHMWSG', 'B000KHMWMC', 'B000KOQFB4', 'B000KOQKXW', 'B000KOSIQY', 'B000KOSD64', 'B000KOUKK6', 'B000KOWGHQ', 'B000KOWGYY', 'B000L9OOMK', 'B000LKVLGQ', 'B000LKVI14', 'B000LKXFBK', 'B000LKXGQO', 'B000LKXJV6', 'B000LKZAAY', 'B000LKZABI', 'B000LLHQAA', 'B000LLM9GQ', 'B000LQJEB4', 'B000LQLH96', 'B000LQOD2O', 'B000LR2OU6', 'B000LR4FAS', 'B000LR4E90', 'B000LR0LC4', 'B000LR4GTS', 'B000LR2P5K', 'B000LR7QMW', 'B000LR2OO2', 'B000LRH7BW', 'B000LRH7A8', 'B000LRIJ82', 'B000LRKOQC', 'B000LXB9TC', 'B000MDCDOG', 'B000MDCDNM', 'B000MDHHGU', 'B000MDHHOC', 'B000MT5194', 'B000N1636G', 'B000N1662M', 'B000NQA1EG', 'B000NRG4TQ', 'B000P0TYH0', 'B000P0VRYI', 'B000QDTIP4', 'B000QF3V82', 'B000QF78AY', 'B000QGK3G4', 'B000QJCNEG', 'B000QWXHK2', 'B000QYFTNS', 'B000R95EG4', 'B000RUNTH4', 'B000S4EGCG', 'B000SRGEXW', 'B000UCPI3M', 'B000UCR92U', 'B000UHAA2Q', 'B000UH8GR2', 'B000UQ2L7Y', 'B000UQ9Q5O', 'B000UWCZGK', 'B000UXA0LG', 'B000UXFI2M', 'B000UXHCZ8', 'B000UZXSZY', 'B000UZXT0I', 'B000V1X7N0', 'B000V760QK', 'B000VDT1ME', 'B000VK4906', 'B000VR8ZBS', 'B000WJ0NRO', 'B000WLW9HO', 'B000XKSJAA', 'B000YG4SJE', 'B000YME4MO', 'B000ZHEO1O', 'B00122729M', 'B00122CLSO', 'B00122E5T2', 'B00122E5SS', 'B00126WGIK', 'B0012LCUXQ', 'B0014CZJC2', 'B0014D2DQ6', 'B0014D2DNY', 'B0014D5PBQ', 'B0014D5PC0', 'B0014D5P70', 'B0014GX9KM', 'B0014GZERS', 'B0014H18AY', 'B0014H18J0', 'B0014H18L8', 'B0015H19T8', 'B0016CMVZI', 'B0017TZ7YW', 'B0019KO5SI', 'B0019ZAILQ', 'B001A38ZH6', 'B001AWBZRO', 'B001AWDGXA', 'B001CA5O94', 'B001CB9PPM', 'B001CEDW26', 'B001CEG0VG', 'B001CEJ86K', 'B001DDCS62', 'B001E52TJA', 'B001EHEE14', 'B001EO5KWY', 'B001EO5U24', 'B001EO69AG', 'B001EO6FRI', 'B001EO7E0K', 'B001EO7G8K', 'B001EO7J0U', 'B001EO7ISS', 'B001EO7OAA', 'B001EO7IYM', 'B001EPP9LK', 'B001EPPFPU', 'B001EPPFXM', 'B001EPPG3Q', 'B001EPPG9A', 'B001EPPKPK', 'B001EPPKQE', 'B001EPQ8MY', 'B001EQ4IOS', 'B001EQ4L7M', 'B001EQ4Z3M', 'B001EQ5KKO', 'B001EQ5LLC', 'B001EQ5RCA', 'B001F5EOXI', 'B001FA1JKY', 'B001FA1MHE', 'B001G0MC40', 'B001G0NZWS', 'B001G0NZXM', 'B001G3ZT92', 'B001GVIUEA', 'B001GVIUDQ', 'B001GVIUFY', 'B001GVIT8C', 'B001H32G4C', 'B001H32FUC', 'B001H32FSO', 'B001H32FRA', 'B001HNXP4C', 'B001HNXOGQ', 'B001HO1XTK', 'B001HO1XVI', 'B001HTFYLI', 'B001HTI3BQ', 'B001HTI5I2', 'B001HTIEJ2', 'B001HTIEEW', 'B001HTKN50', 'B001HTOZ9A', 'B001HTOXHY', 'B001HW4GQ4', 'B001HWBFBS', 'B001HWPRIU', 'B001HWT0EC', 'B001HWUYCY', 'B001HWT0JW', 'B001HWT0LA', 'B001HWROUO', 'B001HWXO1C', 'B001HWWQ8E', 'B001HX0LG2', 'B001HX0KQI', 'B001HX2HSW', 'B001HX1O0E', 'B001HX2NEU', 'B001HX2JDA', 'B001HX85QK', 'B001HX9PNC', 'B001I7PZB8', 'B001IH8ERA', 'B001IHOLDQ', 'B001IHV0B2', 'B001IHUJQE', 'B001IHUXCY', 'B001IJCL8G', 'B001IJDKG8', 'B001IJJBHA', 'B001IZ60S2', 'B001IZEJB2', 'B001IZIDVY', 'B001IZK6SW', 'B001IZK5V0', 'B001IZK5PQ', 'B001IZM8WO', 'B001KY0960', 'B001L02ZAG', 'B001L492LW', 'B001LM5VFK', 'B001M08X3S', 'B001M1V4Q0', 'B001M555O8', 'B001NO4A8K', 'B001NO6EA2', 'B001SAWLU8', 'B001SAX7CY', 'B001SAYWDM', 'B001SAZ5LA', 'B001SAYHVY', 'B001SAZ4R0', 'B001SB12P2', 'B001SB14FK', 'B001SB42D6', 'B001SB4Q0A', 'B001SB8AZC', 'B001TZOAOC', 'B001U6JSVK', 'B001UFQ2ME', 'B001UFU13A', 'B001YJBN0M', 'B0021491QM', 'B0025UALB6', 'B0025UAMC4', 'B0025UCNKI', 'B0025UCP4W', 'B0025VF8FY', 'B0026LP6XW', 'B0028GWJA8', 'B0029K162K', 'B002BXKY9Q', 'B002C58LDY', 'B002CRD6DM', 'B002ESDVJS', 'B002EY5TTW', 'B002EYBB3A', 'B002HQEYO8', 'B002IIPRIM', 'B002K6JHYW', 'B002QRSP20', 'B002QX4RGW', 'B002SCF6DO', 'B002T5YW94', 'B002T644GO', 'B002T63ESI', 'B002XPNF9S', 'B002XPPAP0', 'B002ZOPX0Q', 'B0030CYIRQ', 'B0030F050C', 'B0036BVLSA', 'B00374YHIM', 'B003B4NK3Q', 'B003EYXUS8', 'B003EZ1SJK', 'B003ILIFOG', 'B003ILNZPK', 'B003ILIJOM', 'B003IMG41Q', 'B003IWV3U8', 'B003J9BCRO', 'B003K1IK58', 'B003K1CQ94', 'B003L1KAUK', 'B003M2VN8G', 'B003MZ85X4', 'B003PPAS9K', 'B003R1Q1IY', 'B003R1VM60', 'B003RWVFEI', 'B003SBRNAS', 'B003SBRVAU', 'B003SBRSR6', 'B003SBRNKI', 'B003SBU3NW', 'B003SBXK6Y', 'B003SBU1VG', 'B003SO2Y1I', 'B003SO2XOQ', 'B003SO6PUY', 'B003SO8QWO', 'B003SWOYKY', 'B003T00ES6', 'B003UMWV66', 'B003UN12PQ', 'B003VKTHRI', 'B003VKWXTC', 'B003WQKIGK', 'B003WT31IY', 'B003XP5ZEA', 'B003Y5LVN8', 'B003YD68QA', 'B003YHKKTM', 'B003ZJSACI', 'B0040WHMFU', 'B00418U69M', 'B0041OOQME', 'B00438IRIM', 'B00438ITAI', 'B00438KUDM', 'B0043CXY9U', 'B0043OGR1K', 'B0043XEL28', 'B00443B2GU', 'B00445RVP4', 'B0046LHAK2', 'B0046LH9FS', 'B0046LDQPK', 'B0046LFAOK', 'B00473PVE6', 'B00474CCRE', 'B00474FZ3C', 'B0048IMA58', 'B0049ATNE6', 'B004AGA186', 'B004AHBDYG', 'B004AHIBB4', 'B004CD4PM0', 'B004CP8JIO', 'B004CT3ITK', 'B004CT3IXG', 'B004CVDV3Q', 'B004DBS3RE', 'B004DJDIPI', 'B004DRCC2A', 'B004E3PWD4', 'B004FOWE4C', 'B004H4LJAA', 'B004H4SF02', 'B004ILTNTG', 'B004J2BEXW', 'B004JAXIIS', 'B004JMKF2I', 'B004JMH7VK', 'B004KET2WE', 'B004KU05BA', 'B004LLBASU', 'B004LLD8G2', 'B004LLD7S6', 'B004N8GWLG', 'B004NRW7TS', 'B004RUBCOM', 'B004RUGY8Q', 'B004RUN2TA', 'B004RUGYMM', 'B004RUN3ZI', 'B004T33LOQ', 'B004TDTZEG', 'B004TSN88U', 'B004TSN6I2', 'B004UB6FU4', 'B004UB5WIK', 'B004UEWNR0', 'B004UITA6S', 'B004ULS3DQ', 'B004VDH4L0', 'B004VDH4LA', 'B004VDH4BU', 'B004VDH5BE', 'B004VDH4LU', 'B004VG36Z0', 'B004W43H3W', 'B004WLNHIA', 'B004X1CFA0', 'B004XM4LEW', 'B004XUHB8C', 'B004XWOPC0', 'B004XWOQZ6', 'B004XXXT6C', 'B004Y6HV7Q', 'B004YAKFBQ', 'B004YT2ZWO', 'B004YT2ZYC', 'B004YV7ZL8', 'B004YV8012', 'B004YV80QW', 'B004ZV0OT2', 'B0050ILYRA', 'B0050ILV6O', 'B00513J44E', 'B0051OL2HU', 'B00529PDV0', 'B00529PC16', 'B0052P1E94', 'B0053B70NG', 'B0053B6ZS2', 'B00542YGK4', 'B00542YH6W', 'B0054MP5ZY', 'B0054RVBPW', 'B005547004', 'B0055Q7VM4', 'B0056BE53Q', 'B0056YT4M0', 'B0058DLW5G', 'B0058FJ7XS', 'B0058FJ7WO', 'B0058FJ8DW', 'B0058FJ8C8', 'B0059HMM3M', 'B0059TZ0AM', 'B005AJDFAI', 'B005AK6YNC', 'B005AYMWZM', 'B005BD7P5Y', 'B005BHYSXM', 'B005BHYOO0', 'B005BHZ9HQ', 'B005DI9X4I', 'B005EH9BZE', 'B005EXPAGM', 'B005FCHK4C', 'B005G4RWTM', 'B005G4S1EW', 'B005G4U9NS', 'B005GAK4DC', 'B005GTVXRO', 'B005HH2BAI', 'B005HH2ASG', 'B005HH2AQS', 'B005HH2AS6', 'B005HH2BBW', 'B005HH2BE4', 'B005HH2ATK', 'B005HHTKA2', 'B005HYH3F4', 'B005JD0YZO', 'B005L4L482', 'B005LPD86C', 'B005LR02VE', 'B005M1EKHQ', 'B005MH04BG', 'B005NDVRJ2', 'B005Q3IQ70', 'B005R1PDQ8', 'B005ROXBD2', 'B005SCYBT6', 'B005STWST4', 'B005T48L5S', 'B005T87ZCY', 'B005UHJZ54', 'B005WE8WEK', 'B005X4AJAO', 'B005XCQE96', 'B005YJ43DC', 'B005YQ1RO8', 'B005ZO6F8W', 'B005ZTLZXM', 'B0060OOTNY', 'B0064JCY5K', 'B0064U3OGC', 'B00650HANY', 'B0069FTZJ2', 'B006AYRMM4', 'B006D9688U', 'B006J187QS', 'B006JP2VJS', 'B006JTRXX8', 'B006JX51AQ', 'B006JY0SZI', 'B006MN4VF4', 'B006NAJE94', 'B006NAF2KO', 'B006O46IVG', 'B006O87AXW', 'B006O87CFS', 'B006OCIJ1K', 'B006R6P4L6', 'B006SMJTII', 'B006U0QVMK', 'B006U48J3A', 'B006VG01FG', 'B006VG0494', 'B006VGIUZE', 'B006VGN4HS', 'B006X1MGUM', 'B006XYXQXK', 'B006ZGE4AU', 'B006ZGE496', 'B006ZGE40K', 'B0072D5SL4', 'B0072UH64O', 'B0075ID1F6', 'B0075W1NIO', 'B00763AVBW', 'B0076ZQLH8', 'B0076ZQNIA', 'B0078DOZ9E', 'B0078DP4PS', 'B0078DR9Y2', 'B0078Q9RD0', 'B007B0ZN3Q', 'B007F1LSL2', 'B007FF6OPI', 'B007FFR89E', 'B007GIPDQ0', 'B007H3CC2C', 'B007HSLHI2', 'B007IW453G', 'B007JER80K', 'B007JEYVKA', 'B007K1KJRG', 'B007N0PGM2', 'B007N7CNEE', 'B007O76Z1U', 'B007QOJ0OA', 'B007RPMQPI', 'B007RPPHAO', 'B007RQUJ5G', 'B007UN778I', 'B007VNRUIY', 'B007VQHY0A', 'B007W5PW2C', 'B007XYQHUS', 'B007YZHD4A', 'B007Z94FKU', 'B00810534O', 'B0080ZYX64', 'B00812UJTG', 'B00817210Q', 'B0083JUMD0', 'B0083OZVOA', 'B0083TMBCA', 'B0083TMAFS', 'B0083WZQ92', 'B0085OQC3C', 'B0085P6LHS', 'B0087AVHYS', 'B00886KZDU', 'B0089CK1T6', 'B008F7S8ZY', 'B008I56D14', 'B008IY7738', 'B008L0IFPI', 'B008MFKFTG', 'B008PCWXI2', 'B008REY5EI', 'B008SDVAGY', 'B008V1YE0M', 'B008VIG08Y', 'B008VSWLG4', 'B008X9Y646', 'B008XF90KK', 'B008XJXDC2', 'B008ZXOQWW', 'B0092G0F9E', 'B0092IAQHI', 'B0093I5AN2', 'B0093UGXBS', 'B00942QFPO', 'B0094B7BBC', 'B0095FB136', 'B0095MHTAI', 'B0095MZLEY', 'B0095OLMYA', 'B0096RWKHO', 'B0096T8AAI', 'B0096TTQII', 'B0097X0NXU', 'B0098J39E8', 'B0098SPCH6', 'B0098SPBVS', 'B0098SPCRG', 'B009AVT5EW', 'B009E6U470', 'B009ETNY56', 'B009GOW6VC', 'B009JQK1Q4', 'B009LA669Y', 'B009S1DH7A', 'B009S1NZ6I', 'B009VNZEEE', 'B009W3RD42', 'B009YX2OBW', 'B009Z1N2OG', 'B009Z7OHT4', 'B00A73Q2GG', 'B00A8I7B6K', 'B00A8R9PDS', 'B00A9HAJ7I', 'B00A9Z84ZY', 'B00AB2NQOO', 'B00ADSTNHU', 'B00AECMKBG', 'B00AECNL78', 'B00AHLKC3M', 'B00ALINKEY', 'B00AQ3D2QU', 'B00ATTFD2M', 'B00AVRH4A6', 'B00AWR0AGU', 'B00AXPWS5C', 'B00AYLWSOQ', 'B00B0406ZY', 'B00B04CVTS', 'B00B0P6XYQ', 'B00B142XJU', 'B00B1DNCYG', 'B00B29Q7JQ', 'B00B4ZLTGE', 'B00B7QS710', 'B00BA73UQ8', 'B00BCKFYC6', 'B00BE1YDZ2', 'B00BIYJD9G', 'B00BJSN6XU', 'B00BJSSWD4', 'B00BOUMRRE', 'B00BP3Q58M', 'B00BP3Q5V4', 'B00BP3Q4AQ', 'B00BP3Q38O', 'B00BPNZIEY', 'B00BQTIBPA', 'B00BQZY5ZO', 'B00BTGUA9A', 'B00BTRQZQ6', 'B00BTRWMNG', 'B00C0WH8WY', 'B00C0WHFQI', 'B00C16BS7U', 'B00C1L7FEK', 'B00C1L90U2', 'B00C2IA4N6', 'B00C37S8W0', 'B00C37S9O2', 'B00C3NBWOA', 'B00C4GPYPY', 'B00C4YIKVQ', 'B00C7C6238', 'B00C7DOSEW', 'B00C9OMCZQ', 'B00C9P8KQK', 'B00C9QYLSA', 'B00CB8IIGM', 'B00CDA2M6K', 'B00CEWL7E0', 'B00CEWL9AC', 'B00CEWL9BG', 'B00CHTSWQQ', 'B00CHTVJ3O', 'B00CHUHWYI', 'B00CHWMXCW', 'B00CHWOK3W', 'B00CJ8L8SE', 'B00CJUB62K', 'B00CKY24TO', 'B00CNV341Q', 'B00CNV2E26', 'B00CNV3JF2', 'B00CNW8QOU', 'B00CNXUXYU', 'B00CO5LG1G', 'B00CP6CIDY', 'B00CPSHSOQ', 'B00CPU2IFS', 'B00CQ7PUIM', 'B00CQEBBDI', 'B00CTLAUEO', 'B00CXXIPP4', 'B00CZ2HT6O', 'B00D3P11T8', 'B00D3PSD4E', 'B00D3RM3XY', 'B00D5L0UEW', 'B00D5KS0DQ', 'B00D7VGJKY', 'B00D8XDVNE', 'B00DAO8EEW', 'B00DBLZOVU', 'B00DDG82S0', 'B00DDG90AY', 'B00DETSUUG', 'B00DEU1LYM', 'B00DGDIZDW', 'B00DHKQXBU', 'B00DHU1DJM', 'B00DIACIF4', 'B00DIJ4JNO', 'B00DJ32FHQ', 'B00DJGEDLY', 'B00DJHTWVE', 'B00DJLKN36', 'B00DJLKM1Y', 'B00DJLKQTW', 'B00DJLKLZG', 'B00DJLKPT8', 'B00DJLKN0Y', 'B00DJLKZNY', 'B00DJLKSBI', 'B00DJLKLV0', 'B00DLB796S', 'B00DLGZBJA', 'B00DM0SBWO', 'B00DO78MJ2', 'B00DPEDYNS', 'B00DRIJ13Y', 'B00DUXN7YK', 'B00DV2LS82', 'B00DVXSKLE', 'B00DYGQIOE', 'B00DYGQ4AM', 'B00DYHHTXC', 'B00DYGQINK', 'B00DYWRZGI', 'B00DZ0P746', 'B00DZ1540C', 'B00DZ117MQ', 'B00E0N4WHU', 'B00E1MICEO', 'B00E1MWRMM', 'B00E1QEAF0', 'B00E1QEC12', 'B00E1QEJ0G', 'B00E1TDFSK', 'B00E21KM2Y', 'B00E341ZAS', 'B00E341Z1W', 'B00E3QNEGY', 'B00E3QNFF4', 'B00E3UUDBE', 'B00E532RR2', 'B00E5BIBUQ', 'B00E5O56M4', 'B00E5TEI9G', 'B00E5U1UY6', 'B00E6WYNYW', 'B00E6XLJX4', 'B00E762C5Y', 'B00E762CJ0', 'B00E78SIJQ', 'B00E7CZYZ8', 'B00E8IFXXO', 'B00EARZK22', 'B00EB4JDAO', 'B00EC9IPE8', 'B00EENB3BO', 'B00EFTJ86Y', 'B00EQD5584', 'B00ERDGBAO', 'B00ETA7XFM', 'B00EV4ZU7E', 'B00F1LV0RU', 'B00F1LV14C', 'B00F6MLHEU', 'B00F80Z6JM', 'B00F80Z480', 'B00F80Z3BI', 'B00F9XC4IY', 'B00F9XCEMK', 'B00F9XC880', 'B00FA39P44', 'B00FA3ZF20', 'B00FA49CZU', 'B00FA4FR7M', 'B00FA4LTG0', 'B00FA4K6AA', 'B00FA4GQFO', 'B00FAQNKPG', 'B00FDM5IE8', 'B00FDM80IE', 'B00FDM87OG', 'B00FDM87IW', 'B00FDQ7SDS', 'B00FDQ7ODM', 'B00FDQ7OK0', 'B00FDQ7SCE', 'B00FDQ7RRK', 'B00FFG6SV4', 'B00FGKCRPK', 'B00FGTR6I4', 'B00FGTRERM', 'B00FI6P7Y0', 'B00FKCM3D0', 'B00FLY3NOA', 'B00FLY3NY0', 'B00FLY3O4E', 'B00FMFKUDA', 'B00FMF4YVO', 'B00FOLTDLW', 'B00FOTKWPA', 'B00FS59U6C', 'B00FSAZYVM', 'B00FTBBFNG', 'B00FZ71B4C', 'B00FZMDOHY', 'B00G6A7UU6', 'B00GB24ZJI', 'B00GBFYJEG', 'B00GBQ7XXY', 'B00GBQ6QGE', 'B00GBQ5QMY', 'B00GCF82V6', 'B00GCFRWNA', 'B00GCQ62FI', 'B00GFH6Z88', 'B00GG7SXXM', 'B00GG9612K', 'B00GGFMA0G', 'B00GGMMVW6', 'B00GHUHO92', 'B00GHVITPE', 'B00GK54212', 'B00GK81U28', 'B00GK83LXY', 'B00GK88SKU', 'B00GL3RNFU', 'B00GOKTMFO', 'B00GPMHCF8', 'B00GPMHCDK', 'B00GPMHCZS', 'B00GS4W9E2', 'B00GW1JRA0', 'B00GW55QS8', 'B00GW59ZLM', 'B00GWGJH8M', 'B00GY052M6', 'B00GYW9P2W', 'B00H02DHFG', 'B00H03QBQC', 'B00H3T4JNK', 'B00H3T856M', 'B00H4G0HOM', 'B00H4GF2L0', 'B00H8PA4GA', 'B00HALO5MQ', 'B00HALSI1A', 'B00HCNJ0N6', 'B00HIP7IEG', 'B00HLOOBVC', 'B00HNPX76E', 'B00HWJ2X6G', 'B00HWJMBPO', 'B00HWJIOLO', 'B00HWWPGJO', 'B00HXRZQ8O', 'B00I1AMVA8', 'B00I1LL7A2', 'B00I1MU64E', 'B00I2B3MQ8', 'B00I3K2FG6', 'B00I49CZ2A', 'B00I49EIWA', 'B00I49FQYO', 'B00I7JWFK4', 'B00IAA1JVG', 'B00IB3BLYW', 'B00ICT49MG', 'B00ICT7DVU', 'B00IFOEJOQ', 'B00IG726RY', 'B00IGJFAM0', 'B00IGPKF7Y', 'B00II1U1ZM', 'B00IJ2FLQO', 'B00IJJ31RS', 'B00ILCCDKY', 'B00IMN67WW', 'B00IRICJQA', 'B00IXD7L08', 'B00IZICOT4', 'B00IZM638I', 'B00J0ELXIK', 'B00J0FF498', 'B00J1SDV7Q', 'B00J2KVAOO', 'B00J4256HM', 'B00J4B1O6A', 'B00J566KH2', 'B00J871EB0', 'B00J871HCG', 'B00J871DAC', 'B00J8XSBUQ', 'B00JAOUIPE', 'B00JBJA03S', 'B00JCA1GJI', 'B00JCA1LT8', 'B00JD1VKRE', 'B00JD4ER1C', 'B00JH4O1XW', 'B00JJAQBF0', 'B00JJAYHOC', 'B00JJAXGF8', 'B00JJUAI86', 'B00JMRRHT4', 'B00JMSBSXY', 'B00JNB1EUW', 'B00JSVKC1O', 'B00JSVKBQU', 'B00JT3VRPQ', 'B00K0R2G1O', 'B00K1RIVDA', 'B00K5TPRS6', 'B00K6AOYJW', 'B00K6KYV2C', 'B00K86VLOU', 'B00KCA2VXC', 'B00KCS0HCQ', 'B00KCSB6N0', 'B00KH5YD8I', 'B00KH6FGP6', 'B00KI3FFJ0', 'B00KIG3SX2', 'B00KLJ4I9O', 'B00KM6W1B8', 'B00KN03EHI', 'B00KN8NG2I', 'B00KOCKFQS', 'B00KPSSQ4Y', 'B00KPSUGCY', 'B00KPVTNWA', 'B00KPWFQ02', 'B00KPWELTY', 'B00KPWFYN6', 'B00KY6P2VM', 'B00LCYI9GK', 'B00LHVSACQ', 'B00LJMYAUO', 'B00LK09BRC', 'B00LKJ6ZFY', 'B00LOB0YVE', 'B00LUXFYQG', 'B00LX4Q5FG', 'B00LYWTSJ2', 'B00M5HO8LI', 'B00M8AX2GO', 'B00M8Y0URO', 'B00MI9K40M', 'B00MJ44PJ2', 'B00MK4ZGRG', 'B00MK4QBG6', 'B00MLR929A', 'B00MN3LYNO', 'B00MPTQU0I', 'B00MSTQNBQ', 'B00MTW5L6U', 'B00MUAGFKC', 'B00MWMVSGY', 'B00MWTXAE0', 'B00MWTQRT0', 'B00MWU94NA', 'B00MWU28WO', 'B00MZHWZN6', 'B00N1UBG7M', 'B00N1UMGWG', 'B00N6VDBOM', 'B00N7JWIS8', 'B00NBK7JMI', 'B00NE7GVAO', 'B00NGTOLA2', 'B00NHWGTZ8', 'B00NHXK8P4', 'B00NLVM6WK', 'B00NLVWT3Q', 'B00NM4I3RI', 'B00NMDJRXS', 'B00NMOCYDC', 'B00NMQMC46', 'B00NQB7X0K', 'B00NR8O30K', 'B00NRBGPV2', 'B00NRCFYM2', 'B00NS5KGIA', 'B00O0PQMJE', 'B00O32OPAC', 'B00O7OD11K', 'B00OD4EMHG', 'B00OI2QTFQ', 'B00OIB72NU', 'B00OICS42W', 'B00OKEOAIU', 'B00OLDP59S', 'B00OM95PUU', 'B00ON4P4M8', 'B00ON4OYN8', 'B00ON4P7HU', 'B00OYJTHIY', 'B00OZQSJI0', 'B00OZQPV36', 'B00OZQUSM0', 'B00P06OKEG', 'B00P076CJG', 'B00P4PQK50', 'B00P5OL3WK', 'B00PE17DH8', 'B00PEDABT8', 'B00PEGEJFM', 'B00PEGAKOG', 'B00PEZC7U2', 'B00PGRAFIE', 'B00PPVB5YO', 'B00PRAWHFY', 'B00PUPSYTE', 'B00PUZ9T5C', 'B00Q2T77DG', 'B00Q9F3XYA', 'B00QAFDHQI', 'B00QG2A4Y8', 'B00QGEQ59Y', 'B00QKVTQ3U', 'B00QL6JQT8', 'B00QOUSP9S', 'B00QSQA8TS', 'B00QSQA2C6', 'B00QSQA8GQ', 'B00QSQA104', 'B00QSQA40G', 'B00QTKSXH2', 'B00QTKTATW', 'B00QWED7NK', 'B00R1MRC92', 'B00R8COSTM', 'B00RD94YLC', 'B00RD95204', 'B00REQ7H2M', 'B00RGZIRZ2', 'B00RHX9S6A', 'B00RNBMZT8', 'B00RNEFOMK', 'B00RPSWIWI', 'B00RW5ZR1I', 'B00S47UQHS', 'B00S6HZCEI', 'B00S98EZAQ', 'B00SIMFD2C', 'B00SP548PK', 'B00SXIVOGA', 'B00SYP6Q2Y', 'B00T0NDEOM', 'B00T2E17WA', 'B00T2ZIEXY', 'B00T2ZL0YO', 'B00TFRBF12', 'B00THGF9A4', 'B00TOUDQKI', 'B00TQKFL1S', 'B00TSTDP60', 'B00TY3LBP2', 'B00TZTS2SO', 'B00U1D588U', 'B00U1D59S4', 'B00U2EM3UO', 'B00U2EM4C6', 'B00U479WR6', 'B00U80XZMC', 'B00U9WNLTQ', 'B00UEJ00KC', 'B00UJTU1M4', 'B00UQTU61S', 'B00V7EQMCI', 'B00V7OWMR2', 'B00W1YC7G8', 'B00W1YJCR0', 'B00W3SQ4C0', 'B00WAISBB0', 'B00WB87N9K', 'B00WDWNC94', 'B00WFSY8SK', 'B00WFU3NR0', 'B00WGSPAGI', 'B00WGSSC68', 'B00WGSW9BW', 'B00WT2M730', 'B00XQMDIIK', 'B00YCQQR78', 'B00YSW3BL6', 'B00YUQSM28', 'B00YWAWH6Y', 'B00ZA189ZC', 'B00ZA19FNM', 'B00ZA1A8EC', 'B00ZBCCSXY', 'B00ZGT3BCY', 'B01096EO7E', 'B010CIL7EC', 'B010MMV3P6', 'B010OTCR3E', 'B011N9HV6C', 'B011UH5BJ6', 'B0121DU1BQ', 'B012HC98HY', 'B012XH71FY', 'B0132GLIOK', 'B013L63PMY', 'B013ORK1LS', 'B013ORKKV4', 'B013ORKOKQ', 'B01498CF0G', 'B01498QEHQ', 'B0149LFOXS', 'B0149LFV04', 'B014INW3UY', 'B014MAE8E2', 'B014MAE5O0', 'B014MAECNO', 'B014QPHRIM', 'B014VPOIPW', 'B014Z5EGX2', 'B014ZCI9O2', 'B014ZCI44W', 'B0158JS1IK', 'B0159BT1P4', 'B015GBJVHU', 'B015GKDVRM', 'B015J54VM8', 'B015PTCSSW', 'B015R3C3AE', 'B016P0S1WW', 'B016P1GLUU', 'B016P3BZPY', 'B0171PYPF2', 'B0173GV8ZY', 'B0173GV5YS', 'B0173KHTYY', 'B0179BQHQ8', 'B017A47UDS', 'B017IR1QBE', 'B017J9X8IA', 'B017MHENWE', 'B017NWKQX8', 'B017WIY66G', 'B017Y91UUS', 'B018FCQ954', 'B0190ZQZ40', 'B0199AXOEA', 'B019CS7SHI', 'B019EBQ3C4', 'B019HP2SZI', 'B019I6AQ1O', 'B019JNHC6I', 'B019JNHJVQ', 'B019WTU6KS', 'B019YHSYXO', 'B019YHTJJW', 'B019YHT352', 'B019YHTF7S', 'B019YHT9K6', 'B019YHTJNI', 'B019YHT9W4', 'B019YHT938', 'B019YHTJ2E', 'B019YHTDZM', 'B019YHTDMK', 'B019YHTDXO', 'B01AII6TEO', 'B01AMJ6WTG', 'B01AYEI6L6', 'B01B5Q96ZM', 'B01BG1S23S', 'B01BXD503O', 'B01CD6ZMJ2', 'B01DL2JRKM', 'B01DPQ4YLQ', 'B01DTJFZ0I', 'B01E5WZR2Y', 'B01EEBRK5I', 'B01ENU0MN2', 'B01EWC8UZS', 'B01F1G45UI', 'B01FG3SJK8', 'B01FGAKJHW', 'B01FR2EPHE', 'B01FR5II4C', 'B01FR5O5QM', 'B01FRP21K4', 'B01FRP22O4', 'B01FWT1S2W', 'B01FWT1OTE', 'B01FWT1R5K', 'B01GG8MZTI', 'B01GITHCLQ', 'B01GKI3XEU', 'B01GKIH71U', 'B01GXWW1UU', 'B01H0ER7U4', 'B01H0ER7ZO', 'B01H74NYMC', 'B01H7RWCOA', 'B01HDZY8K2', 'B01HISCL7G']

In [7]:
ama_meta_df = pd.DataFrame(ama_meta_trim)
ama_meta_df

           fish                                               name        asin
0     Tuna Fish  Goya Stuffed Olive with Minced Tuna 5.25 ounce...  5643467860
1      Sardines                   Sardine In Tomato Sauce W/ Chili  B0000D17CF
2      Crabmeat                    1 lb. Fresh Jumbo Lump Crabmeat  B0000SX9YQ
3       Seafood                          Fresh Jumbo Shrimp, 2 Lbs  B0000SX9U0
4      Sardines  Portuguese Sardines - with Hot Pepper in Olive...  B0000TUA7O
...         ...                                                ...         ...
1269      Clams  Crown Prince Smoked Baby Clams in Oil, 3.75 Ou...  B01H0ER7ZO
1270     Salmon  StarKist Salmon Creations Pouches, Lemon Dill,...  B01H74NYMC
1271  Tuna Fish  Starkist Tuna Creations Variety Pack, 2.6-Ounc...  B01H7RWCOA
1272   Sardines  Matiz Sardines and Octopus Pulpo in Olive oil ...  B01HDZY8K2
1273   Sardines  Brisling Sardines in Olive Oil, 5.6-Ounce Cans...  B01HISCL7G

[1274 rows x 3 columns]

In [9]:
ama_meta_df.drop_duplicates(inplace=True)

In [11]:
#Reading in the reviews
ama_rev = []

for i in parse(rev_path):
    ama_rev.append(i)

In [ ]:
#Cutting out all of the reviews that aren't for tinned/canned fish
ama_rev_trim = []
i = 0
for entry in ama_rev:

    #Checking for asin code matches in the list of products in the tinned/canned fish category
    if entry['asin'] in asin:
        
        if 'reviewText' in entry.keys():
            
            #Storing the crucial data from each review
            review = {'rating': entry['overall'], 'verified': entry['verified'], 'date': entry['unixReviewTime'],
                     'description': entry['reviewText'], 'summary': entry['summary'], 'asin': entry['asin']}

            ama_rev_trim.append(review)
    print (i)
    i+=1

In [14]:
ama_rev_df = pd.DataFrame(ama_rev_trim)
ama_rev_df

,rating,verified,date,description,summary,asin
0,3.0,True,1358035200,It looks like Caspian caviar and a taste a lit...,You get what you paid for,B00017Y986
1,5.0,True,1346284800,I purchased the Lumpfish caviar after tasting ...,Very Nice Product!,B00017Y986
2,3.0,True,1331078400,I've had much better for the same price! This ...,It's ok...for the price.,B00017Y986
3,5.0,True,1326758400,"Great quality, Amazing taste, and a wonderful ...",GREAT!,B00017Y986
4,1.0,True,1315094400,I'm feeling like chewing on salty-stale plasti...,Probably you would like it if you like plastic...,B00017Y986
...,...,...,...,...,...,...
11828,5.0,True,1517788800,Delicious. Perfect for an on the go lunch. G...,Perfect for an on the go lunch,B00DYGQINK
11829,5.0,True,1517443200,My family love these. The Ranch and Hickory s...,Great Snack,B00DYGQINK
11830,1.0,True,1517356800,"In general, I love tuna. However, this is the...",I love tuna. However,B00DYGQINK
11831,5.0,True,1517097600,These are awesome for easy work lunches.,Tasty and easy,B00DYGQINK
11832,5.0,True,1517011200,Convenient with outstanding flavor.,Convenient for work,B00DYGQINK

In [15]:
len(ama_rev_trim)

11833

In [21]:
#Use to get rid of unverified reviews
#ama_rev_df.drop(ama_rev_df[ama_rev_df['verified']==False].index, inplace=True)

Int64Index([  113,   114,   181,   182,   186,   188,   189,   197,   204,
              222,
            ...
            11716, 11718, 11719, 11721, 11734, 11735, 11737, 11750, 11774,
            11792],
           dtype='int64', length=1373)

In [17]:
#Merging the review and product info dataframes
ama_combined_df = ama_rev_df.merge(ama_meta_df, on = 'asin')
ama_combined_df

,rating,verified,date,description,summary,asin,fish,name
0,3.0,True,1358035200,It looks like Caspian caviar and a taste a lit...,You get what you paid for,B00017Y986,Caviars & Roes,12 OZ BLACK LUMPFISH CAVIAR
1,5.0,True,1346284800,I purchased the Lumpfish caviar after tasting ...,Very Nice Product!,B00017Y986,Caviars & Roes,12 OZ BLACK LUMPFISH CAVIAR
2,3.0,True,1331078400,I've had much better for the same price! This ...,It's ok...for the price.,B00017Y986,Caviars & Roes,12 OZ BLACK LUMPFISH CAVIAR
3,5.0,True,1326758400,"Great quality, Amazing taste, and a wonderful ...",GREAT!,B00017Y986,Caviars & Roes,12 OZ BLACK LUMPFISH CAVIAR
4,1.0,True,1315094400,I'm feeling like chewing on salty-stale plasti...,Probably you would like it if you like plastic...,B00017Y986,Caviars & Roes,12 OZ BLACK LUMPFISH CAVIAR
...,...,...,...,...,...,...,...,...
11828,5.0,True,1517788800,Delicious. Perfect for an on the go lunch. G...,Perfect for an on the go lunch,B00DYGQINK,Tuna Fish,"StarKist Tuna Creations, Hickory Smoked &ndash..."
11829,5.0,True,1517443200,My family love these. The Ranch and Hickory s...,Great Snack,B00DYGQINK,Tuna Fish,"StarKist Tuna Creations, Hickory Smoked &ndash..."
11830,1.0,True,1517356800,"In general, I love tuna. However, this is the...",I love tuna. However,B00DYGQINK,Tuna Fish,"StarKist Tuna Creations, Hickory Smoked &ndash..."
11831,5.0,True,1517097600,These are awesome for easy work lunches.,Tasty and easy,B00DYGQINK,Tuna Fish,"StarKist Tuna Creations, Hickory Smoked &ndash..."
11832,5.0,True,1517011200,Convenient with outstanding flavor.,Convenient for work,B00DYGQINK,Tuna Fish,"StarKist Tuna Creations, Hickory Smoked &ndash..."

In [18]:
#Checking which species are present in the data
ama_combined_df.fish.unique()

array(['Caviars & Roes', 'Clams', 'Salmon', 'Tuna Fish', 'Anchovies',
       'Sardines', 'Oysters',
       "Black Capelin Caviar is Usually Served as an Appetizer, Hors D'oeuvre, or Side Dish",
       'Mackerel', 'Seafood', 'Herring', 'Crabmeat', 'Mussels & Cockles',
       'Trout'], dtype=object)

In [21]:
#Dropping Caviar since it is not something we're looking at in this analysis and then saving the dataframe
ama_combined_df.drop(ama_combined_df[ama_combined_df['fish'] == 'Caviars & Roes'].index, inplace=True)
ama_combined_df.drop(ama_combined_df[ama_combined_df['fish'] == "Black Capelin Caviar is Usually Served as an Appetizer, Hors D'oeuvre, or Side Dish"].index, inplace=True)
ama_combined_df.reset_index(drop=True, inplace=True)
ama_combined_df.to_csv(csv_folder/'amazon.csv')

In [58]:
#sustainability_df = pd.read_csv(data_folder/'sustainability_data.csv', index_col=0)
#sustainability_df

,Name,Latin Name,Status
0,Acadian Redfish,Sebastes fasciatus,None
1,Acropora globiceps Coral,Acropora globiceps,ESA Threatened
2,Acropora jacquelineae Coral,Acropora jacquelineae,ESA Threatened
3,Acropora lokani Coral,Acropora lokani,ESA Threatened - Foreign
4,Acropora pharaonis Coral,Acropora pharaonis,ESA Threatened - Foreign
...,...,...,...
292,Wreckfish,Polyprion americanus,None
293,Yelloweye Rockfish,Sebastes ruberrimus,ESA Threatened
294,Yellowfin Sole,Limanda aspera,None
295,Yellowtail Flounder,Limanda ferruginea,None
296,Yellowtail Rockfish,Sebastes flavidus,None

In [7]:
#catch_df = pd.read_excel(data_folder/'ICESCatchDataset2006-2021.xlsx', sheet_name= 'North-East Atlantic Catches')
#catch_df

,Species,Area,Units,Country,2021,2020,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007,2006
0,AAS,27,TLW,DK,0,0,0,0,0.00,0.03,0.0,0.0,0.23,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,AAS,27.3,TLW,DK,0,0,0,0,0.00,0.00,0.0,0.0,0.23,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,AAS,27.3.c.22,TLW,DK,0,0,0,0,0.00,0.00,0.0,0.0,0.23,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AAS,27.4,TLW,DK,0,0,0,0,0.00,0.03,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AAS,27.4.b,TLW,DK,0,0,0,0,0.00,0.03,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46681,ZGP,27.9,TLW,ES,0.69,0.51,0.73,0.58,0.31,0.35,0.3,0.2,0.33,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46682,ZGP,27.9.a,TLW,ES,0.69,0.51,0.73,0.58,0.31,0.35,0.3,0.2,0.33,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46683,ZGS,27,TLW,ES,1.41,4.08,3.43,0.54,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46684,ZGS,27.9,TLW,ES,1.41,4.08,3.43,0.54,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46685,ZGS,27.9.a,TLW,ES,1.41,4.08,3.43,0.54,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
#species_df = pd.read_excel(data_folder/'ICESCatchDataset2006-2021.xlsx', sheet_name= 'Species')
#species_df.drop(columns=['Spanish', 'French'], inplace=True)

In [17]:
#catch_df_combined = species_df.merge(catch_df, left_on='FAO_code', right_on='Species')
#catch_df_combined.drop(columns=['FAO_code', 'Species'], inplace=True)

['TLW']